### ISSUE TITLE
"TCGA_HLA_benchmark" Which software is the most accurate?

### ISSUE THREAD

**Issue by jingydz** [biolxy/TCGA_HLA_benchmark#1]

**Comment by haoecust** [comment]
Polysolver,  OptiType, and xHLA are highly recommended to for high efficient and accuracy HLA class I genotyping based on WES data.  If you don't mind calling speed, HLA-PRG-LA is also recommended. You can see details in the https://febs.onlinelibrary.wiley.com/doi/abs/10.1002/1878-0261.12895.

**Comment by jingydz** [comment]
Great job! Thank you for your answer.
