### ISSUE TITLE
No response from Prof. Liu

### ISSUE THREAD

**Issue by jchuhooo** [biolxy/TCGA_HLA_benchmark#3]
Dear manager,
Thank you for the nice benchmark of different HLA typing tools. We would like to access the HLA typing results of TCGA samples, especially the typing result which are consistence in different tools. However, no response was received from Prof Liu with our application, which TCGA raw data access have been provided. May I ask how long will this process take? Or if there's another reviewers that we can apply for such dataset? Thank you.

**Comment by haoecust** [comment]
Dear Jchuhooo,

I'm sorry for the late response. Maybe the previous email was blocked by the email server. It was the first time I received your message.  Since I can not find your email addersss in the github, you can contact me at **_haoye.ecust@gmail.com_**.  

Best

Hao
